        const plantDatabase = [
          {
            id: 1,
            name: 'Coconut Palm',
            layer: 'Canopy',
            climate: 'Tropical',
            symbol: '🌴',
            yieldPerYear:700,
            unit: 'lbs',
            maturityAge: 6,
            scientificName: 'Cocos nucifera',
            description: 'The coconut palm is a versatile tree that provides food, drink, oil, and materials for housing and crafts.',
            uses: ['Food', 'Drink', 'Oil', 'Building material'],
            growthHabit: 'Tall palm tree, can grow up to 100 feet high',
            soil: 'Well-draining, sandy soil',
            sunlight: 'Full sun',
            water: 'Moderate, tolerant of salt spray',
            companions: ['Banana', 'Papaya', 'Sweet Potato'],
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Cocos_nucifera_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-187.jpg/1024px-Cocos_nucifera_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-187.jpg',
            marketPrice: 1.2 // price per lb
        },
                {
                    id: 2,
                    name: 'Mango Tree',
                    layer: 'Canopy',
                    climate: 'Tropical',
                    symbol: '🥭',
                    yieldPerYear: 220,
                    unit: 'lbs',
                    maturityAge: 5,
                    scientificName: 'Mangifera indica',
                    description: 'Mango trees produce sweet, juicy fruits and provide excellent shade.',
                    uses: ['Food', 'Shade'],
                    growthHabit: 'Large evergreen tree, can reach 100 feet',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun',
                    water: 'Moderate, drought-tolerant when established',
                    companions: ['Papaya', 'Banana', 'Lemongrass'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Mangoes_%28Magnifera_indica%29_from_India.jpg/1024px-Mangoes_%28Magnifera_indica%29_from_India.jpg',
                    marketPrice: 3.0 // price per lb
                },
                {
                    id: 3,
                    name: 'Banana',
                    layer: 'Sub-canopy',
                    climate: 'Tropical',
                    symbol: '🍌',
                    yieldPerYear: 88,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Musa spp.',
                    description: 'Fast-growing herb producing clusters of fruits.',
                    uses: ['Food', 'Fiber'],
                    growthHabit: 'Large herb, can reach 20 feet',
                    soil: 'Rich, well-draining soil',
                    sunlight: 'Full sun to partial shade',
                    water: 'High, needs consistent moisture',
                    companions: ['Papaya', 'Sweet Potato', 'Taro'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Musa_JPG01.jpg/1024px-Musa_JPG01.jpg',
                    marketPrice: 1.2 // price per lb
                },
                {
                    id: 4,
                    name: 'Papaya',
                    layer: 'Sub-canopy',
                    climate: 'Tropical',
                    symbol: '🍈',
                    yieldPerYear: 55,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Carica papaya',
                    description: 'Fast-growing tree-like plant with nutritious fruits.',
                    uses: ['Food', 'Medicine'],
                    growthHabit: 'Unbranched tree-like plant, 10-30 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Sweet Potato', 'Lemongrass', 'Marigold'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Carica_papaya_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-029.jpg/330px-Carica_papaya_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-029.jpg',
                    marketPrice: 2.5 // price per lb
                },
                {
                    id: 5,
                    name: 'Coffee',
                    layer: 'Shrub',
                    climate: 'Tropical',
                    symbol: '☕',
                    yieldPerYear: 11,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Coffea arabica',
                    description: 'Evergreen shrub producing coffee beans.',
                    uses: ['Beverage', 'Cosmetics'],
                    growthHabit: 'Shrub or small tree, 6-15 feet tall',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Banana', 'Avocado', 'Macadamia'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Starr_070308-5472_Coffea_arabica.jpg/1920px-Starr_070308-5472_Coffea_arabica.jpg',
                    marketPrice: 15.0 // price per lb
                },
                {
                    id: 6,
                    name: 'Pineapple',
                    layer: 'Herbaceous',
                    climate: 'Tropical',
                    symbol: '🍍',
                    yieldPerYear: 4,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Ananas comosus',
                    description: 'Tropical fruit-bearing plant with spiky leaves.',
                    uses: ['Food', 'Fiber'],
                    growthHabit: 'Herbaceous perennial, 3-5 feet tall',
                    soil: 'Well-draining, sandy loam',
                    sunlight: 'Full sun',
                    water: 'Moderate, drought-tolerant',
                    companions: ['Legumes', 'Comfrey', 'Marigolds'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/7/74/%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg',
                    marketPrice: 4.0 // price per lb
                },
                {
                    id: 7,
                    name: 'Sweet Potato',
                    layer: 'Ground Cover',
                    climate: 'Tropical',
                    symbol: '🍠',
                    yieldPerYear: 11,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Ipomoea batatas',
                    description: 'Creeping vine with edible tubers and leaves.',
                    uses: ['Food', 'Erosion control'],
                    growthHabit: 'Spreading vine',
                    soil: 'Well-draining, sandy loam',
                    sunlight: 'Full sun',
                    water: 'Moderate, drought-tolerant once established',
                    companions: ['Corn', 'Sunflowers', 'Okra'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Genasu_gadde_%28Kannada_%E0%B2%97%E0%B3%86%E0%B2%A3%E0%B2%B8%E0%B3%81_%E0%B2%97%E0%B2%A1%E0%B3%8D%E0%B2%A1%E0%B3%86%29_%2849108875711%29.jpg/1920px-Genasu_gadde_%28Kannada_%E0%B2%97%E0%B3%86%E0%B2%A3%E0%B2%B8%E0%B3%81_%E0%B2%97%E0%B2%A1%E0%B3%8D%E0%B2%A1%E0%B3%86%29_%2849108875711%29.jpg',
                    marketPrice: 4.0 // price per lb
                },
                {
                    id: 8,
                    name: 'Vanilla',
                    layer: 'Vine',
                    climate: 'Tropical',
                    symbol: '🍶',
                    yieldPerYear: 40.4,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Vanilla planifolia',
                    description: 'Climbing orchid vine producing aromatic seed pods.',
                    uses: ['Flavoring', 'Fragrance'],
                    growthHabit: 'Climbing vine, can reach 30 feet',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Partial shade',
                    water: 'High, needs consistent moisture',
                    companions: ['Cacao', 'Black Pepper', 'Turmeric'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/8/82/Vanilla_fragrans_3.jpg',
                    marketPrice: 50.0 // price per lb
                },
                {
                    id: 9,
                    name: 'Turmeric',
                    layer: 'Root',
                    climate: 'Tropical',
                    symbol: '🌿',
                    yieldPerYear: 4,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Curcuma longa',
                    description: 'Herbaceous plant with vibrant yellow rhizomes.',
                    uses: ['Spice', 'Medicine', 'Dye'],
                    growthHabit: 'Herbaceous perennial, 3-4 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Ginger', 'Galangal', 'Cardamom'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Curcuma_longa_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-199.jpg',
                    marketPrice: 3.0 // price per lb
                },
                {
                    id: 10,
                    name: 'Breadfruit',
                    layer: 'Canopy',
                    climate: 'Tropical',
                    symbol: '🍞',
                    yieldPerYear: 440,
                    unit: 'lbs',
                    maturityAge: 5,
                    scientificName: 'Artocarpus altilis',
                    description: 'Large tree producing starchy fruits.',
                    uses: ['Food', 'Timber'],
                    growthHabit: 'Large evergreen tree, can reach 85 feet',
                    soil: 'Well-draining, tolerates various types',
                    sunlight: 'Full sun',
                    water: 'Moderate, tolerates brief dry periods',
                    companions: ['Taro', 'Sweet Potato', 'Cassava'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Artocarpus_altilis_%28fruit%29.jpg/1024px-Artocarpus_altilis_%28fruit%29.jpg',
                    marketPrice: 8.0 // price per lb
                },
                {
                    id: 11,
                    name: 'Jackfruit',
                    layer: 'Canopy',
                    climate: 'Tropical',
                    symbol: '🍈',
                    yieldPerYear: 330,
                    unit: 'lbs',
                    maturityAge: 5,
                    scientificName: 'Artocarpus heterophyllus',
                    description: 'Large tree producing the largest tree-borne fruit.',
                    uses: ['Food', 'Timber'],
                    growthHabit: 'Large evergreen tree, can reach 80 feet',
                    soil: 'Well-draining, tolerates various types',
                    sunlight: 'Full sun',
                    water: 'Moderate, tolerates brief dry periods',
                    companions: ['Pineapple', 'Turmeric', 'Ginger'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Jackfruit_hanging.JPG/1024px-Jackfruit_hanging.JPG',
                    marketPrice: 6.0 // price per lb
                },
                {
                    id: 12,
                    name: 'Cacao',
                    layer: 'Sub-canopy',
                    climate: 'Tropical',
                    symbol: '🍫',
                    yieldPerYear: 2.2,
                    unit: 'lbs',
                    maturityAge: 5,
                    scientificName: 'Theobroma cacao',
                    description: 'Tree producing seeds used to make chocolate.',
                    uses: ['Food', 'Cosmetics'],
                    growthHabit: 'Small evergreen tree, 15-25 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Partial shade',
                    water: 'High, needs consistent moisture',
                    companions: ['Banana', 'Vanilla', 'Cardamom'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Cocoa_Pods.JPG',
                    marketPrice: 4.0 // price per lb
                },
                {
                    id: 13,
                    name: 'Passion Fruit',
                    layer: 'Vine',
                    climate: 'Tropical',
                    symbol: '🍇',
                    yieldPerYear: 33,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Passiflora edulis',
                    description: 'Vigorous vine producing tart, edible fruits.',
                    uses: ['Food', 'Medicine'],
                    growthHabit: 'Climbing vine, can reach 20 feet',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Banana', 'Sweet Potato', 'Marigold'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Unripe_passion_fruit.jpg/1024px-Unripe_passion_fruit.jpg',
                    marketPrice: 2.0 // price per lb
                },
                {
                    id: 14,
                    name: 'Ginger',
                    layer: 'Root',
                    climate: 'Tropical',
                    symbol: '🥭',
                    yieldPerYear: 4.4,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Zingiber officinale',
                    description: 'Herbaceous perennial with aromatic rhizomes.',
                    uses: ['Spice', 'Medicine'],
                    growthHabit: 'Herbaceous perennial, 2-4 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Partial shade',
                    water: 'High, consistent moisture',
                    companions: ['Turmeric', 'Galangal', 'Cardamom'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Koeh-146-no_text.jpg/1024px-Koeh-146-no_text.jpg',
                    marketPrice: 1.6 // price per lb
                },
                {
                    id: 15,
                    name: 'Moringa',
                    layer: 'Sub-canopy',
                    climate: 'Tropical',
                    symbol: '🌳',
                    yieldPerYear: 66,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Moringa oleifera',
                    description: 'Fast-growing tree with nutrient-dense leaves and seed pods.',
                    uses: ['Food', 'Medicine', 'Water purification'],
                    growthHabit: 'Small tree, can reach 30-40 feet',
                    soil: 'Well-draining, tolerates poor soil',
                    sunlight: 'Full sun',
                    water: 'Low, drought-tolerant',
                    companions: ['Lemongrass', 'Sweet Potato', 'Pigeon Pea'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/The_tree_and_seedpods_of_Moringa_oleifera.JPG/1920px-The_tree_and_seedpods_of_Moringa_oleifera.JPG',
                    marketPrice: 20.0 // price per lb
                },
                {
                    id: 16,
                    name: 'Soursop',
                    layer: 'Sub-canopy',
                    climate: 'Tropical',
                    symbol: '🍈',
                    yieldPerYear: 44,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Annona muricata',
                    description: 'Small evergreen tree producing large, spiky fruits.',
                    uses: ['Food', 'Medicine'],
                    growthHabit: 'Small tree, 15-30 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Papaya', 'Banana', 'Pigeon Pea'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Annona_muricata_Blanco1.196.png/1024px-Annona_muricata_Blanco1.196.png',
                    marketPrice: 10.0 // price per lb
                },
                {
                    id: 17,
                    name: 'Guava',
                    layer: 'Shrub',
                    climate: 'Tropical',
                    symbol: '🫒',
                    yieldPerYear: 33,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Psidium guajava',
                    description: 'Shrub or small tree producing aromatic fruits.',
                    uses: ['Food', 'Medicine'],
                    growthHabit: 'Shrub or small tree, 10-25 feet tall',
                    soil: 'Adaptable, prefers well-draining soil',
                    sunlight: 'Full sun',
                    water: 'Moderate, drought-tolerant when established',
                    companions: ['Lemongrass', 'Marigold', 'Chili Pepper'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Goya_blancs.JPG',
                    marketPrice: 1.8 // price per lb
                },
             {
                    id: 18,
                    name: 'Allspice',
                    layer: 'Sub-canopy',
                    climate: 'Tropical',
                    symbol: '🌿',
                    yieldPerYear: 22,
                    unit: 'lbs',
                    maturityAge: 5,
                    scientificName: 'Pimenta dioica',
                    description: 'Evergreen tree with aromatic leaves and berries.',
                    uses: ['Spice', 'Essential oil'],
                    growthHabit: 'Evergreen tree, 30-60 feet tall',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, tolerates brief dry periods',
                    companions: ['Cacao', 'Banana', 'Vanilla'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Pimenta_dioica_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-239.jpg',
                    marketPrice: 10.5 // price per lb
                },
                {
                    id: 19,
                    name: 'Cardamom',
                    layer: 'Herbaceous',
                    climate: 'Tropical',
                    symbol: '🌱',
                    yieldPerYear: 0.44,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Elettaria cardamomum',
                    description: 'Perennial herb producing aromatic seed pods.',
                    uses: ['Spice', 'Medicine'],
                    growthHabit: 'Herbaceous perennial, 6-15 feet tall',
                    soil: 'Rich, well-draining, high in organic matter',
                    sunlight: 'Partial shade',
                    water: 'High, consistent moisture',
                    companions: ['Ginger', 'Turmeric', 'Black Pepper'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Elettaria_cardamomum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-057.jpg',
                    marketPrice: 3.5 // price per lb
                },
                {
                    id: 20,
                    name: 'Cassava',
                    layer: 'Shrub',
                    climate: 'Tropical',
                    symbol: '🥔',
                    yieldPerYear: 22,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Manihot esculenta',
                    description: 'Shrub grown for its edible starchy roots.',
                    uses: ['Food', 'Starch production'],
                    growthHabit: 'Shrub, 6-10 feet tall',
                    soil: 'Well-draining, tolerates poor soil',
                    sunlight: 'Full sun',
                    water: 'Low, drought-tolerant',
                    companions: ['Pigeon Pea', 'Sweet Potato', 'Maize'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Manihot_esculenta_001.jpg/2560px-Manihot_esculenta_001.jpg',
                    marketPrice: 0.8 // price per lb
                },
                {
                    id: 21,
                    name: 'Taro',
                    layer: 'Herbaceous',
                    climate: 'Tropical',
                    symbol: '🌿',
                    yieldPerYear: 13,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Colocasia esculenta',
                    description: 'Herbaceous perennial grown for its edible corms and leaves.',
                    uses: ['Food', 'Medicinal'],
                    growthHabit: 'Herbaceous perennial, 3-6 feet tall',
                    soil: 'Rich, moist soil',
                    sunlight: 'Partial shade to full sun',
                    water: 'High, tolerates waterlogged soils',
                    companions: ['Banana', 'Coconut', 'Sweet Potato'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Songe-R%C3%A9union.JPG',
                    marketPrice: 1.0 // price per lb
                },
                {
                    id: 22,
                    name: 'Black Pepper',
                    layer: 'Vine',
                    climate: 'Tropical',
                    symbol: '🧂',
                    yieldPerYear: 4.4,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Piper nigrum',
                    description: 'Flowering vine cultivated for its fruit, used as a spice.',
                    uses: ['Spice', 'Medicine'],
                    growthHabit: 'Climbing vine, can reach 30 feet',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Partial shade',
                    water: 'Moderate to high, consistent moisture',
                    companions: ['Coffee', 'Vanilla', 'Cardamom'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Piper_nigrum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-107.jpg',
                    marketPrice: 2.5 // price per lb
                },
                {
                    id: 23,
                    name: 'Cinnamon',
                    layer: 'Sub-canopy',
                    climate: 'Tropical',
                    symbol: '🌿',
                    yieldPerYear: 2.2,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Cinnamomum verum',
                    description: 'Small evergreen tree known for its aromatic bark.',
                    uses: ['Spice', 'Essential oil'],
                    growthHabit: 'Evergreen tree, 30-50 feet tall',
                    soil: 'Well-draining, sandy loam',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Clove', 'Nutmeg', 'Allspice'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Cinnamomum_verum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-182.jpg',
                    marketPrice: 3.5 // price per lb
                },
                {
                    id: 24,
                    name: 'Nutmeg',
                    layer: 'Canopy',
                    climate: 'Tropical',
                    symbol: '🌰',
                    yieldPerYear: 11,
                    unit: 'lbs',
                    maturityAge: 7,
                    scientificName: 'Myristica fragrans',
                    description: 'Evergreen tree producing nutmeg and mace.',
                    uses: ['Spice', 'Essential oil'],
                    growthHabit: 'Evergreen tree, 30-60 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Cinnamon', 'Clove', 'Banana'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Myristica_Fragrans_-_%E0%B4%9C%E0%B4%BE%E0%B4%A4%E0%B4%BF%E0%B4%AE%E0%B4%B0%E0%B4%82.JPG/1024px-Myristica_Fragrans_-_%E0%B4%9C%E0%B4%BE%E0%B4%A4%E0%B4%BF%E0%B4%AE%E0%B4%B0%E0%B4%82.JPG',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 25,
                    name: 'Clove',
                    layer: 'Canopy',
                    climate: 'Tropical',
                    symbol: '🌼',
                    yieldPerYear: 8.8,
                    unit: 'lbs',
                    maturityAge: 6,
                    scientificName: 'Syzygium aromaticum',
                    description: 'Evergreen tree cultivated for its aromatic flower buds.',
                    uses: ['Spice', 'Essential oil'],
                    growthHabit: 'Evergreen tree, 25-40 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Nutmeg', 'Cinnamon', 'Allspice'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Syzygium_aromaticum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-030.jpg',
                    marketPrice: 4.0 // price per lb
                },
                {
                    id: 26,
                    name: 'Barbados Cherry',
                    layer: 'Shrub',
                    climate: 'Tropical',
                    symbol: '🍒',
                    yieldPerYear: 66,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Malpighia emarginata',
                    description: 'Shrub known for its fruits high in vitamin C.',
                    uses: ['Food', 'Vitamin C supplement'],
                    growthHabit: 'Shrub or small tree, 10-15 feet tall',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun',
                    water: 'Moderate, drought-tolerant when established',
                    companions: ['Papaya', 'Pineapple', 'Passion Fruit'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Malpighia_glabra_blossom_and_unripe_fruits.jpg/1920px-Malpighia_glabra_blossom_and_unripe_fruits.jpg',
                    marketPrice: 7.5 // price per lb
                },
                {
                    id: 27,
                    name: 'Star Fruit',
                    layer: 'Sub-canopy',
                    climate: 'Tropical',
                    symbol: '🌟',
                    yieldPerYear: 100,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Averrhoa carambola',
                    description: 'Tree producing star-shaped fruits with a sweet-tart flavor.',
                    uses: ['Food', 'Ornamental'],
                    growthHabit: 'Evergreen tree, 20-30 feet tall',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Papaya', 'Banana', 'Pineapple'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Averrhoa_carambola_ARS_k5735-7.jpg',
                    marketPrice: 2.0 // price per lb
                },
                {
                    id: 28,
                    name: 'Rambutan',
                    layer: 'Sub-canopy',
                    climate: 'Tropical',
                    symbol: '🔴',
                    yieldPerYear: 220,
                    unit: 'lbs',
                    maturityAge: 5,
                    scientificName: 'Nephelium lappaceum',
                    description: 'Tree producing sweet fruits with hairy exteriors.',
                    uses: ['Food'],
                    growthHabit: 'Evergreen tree, 40-80 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun',
                    water: 'High, consistent moisture',
                    companions: ['Durian', 'Mangosteen', 'Lychee'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Rambutan_Binjai_Pasar_Baru_Jakarta.JPG',
                    marketPrice: 10.0 // price per lb
                },
                {
                    id: 29,
                    name: 'Lychee',
                    layer: 'Canopy',
                    climate: 'Tropical',
                    symbol: '🔴',
                    yieldPerYear: 110,
                    unit: 'lbs',
                    maturityAge: 5,
                    scientificName: 'Litchi chinensis',
                    description: 'Evergreen tree producing sweet, translucent fruits.',
                    uses: ['Food'],
                    growthHabit: 'Evergreen tree, 30-100 feet tall',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Longan', 'Rambutan', 'Mango'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Litchi_chinensis_fruits.JPG/1920px-Litchi_chinensis_fruits.JPG',
                    marketPrice: 12.0 // price per lb
                },
                {
                    id: 30,
                    name: 'Durian',
                    layer: 'Canopy',
                    climate: 'Tropical',
                    symbol: '🍈',
                    yieldPerYear: 220,
                    unit: 'lbs',
                    maturityAge: 7,
                    scientificName: 'Durio zibethinus',
                    description: 'Large tree producing large, spiky fruits with pungent odor.',
                    uses: ['Food'],
                    growthHabit: 'Evergreen tree, 80-130 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun',
                    water: 'High, consistent moisture',
                    companions: ['Rambutan', 'Mangosteen', 'Jackfruit'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Durio_Zibethinus_Van_Nooten.jpg',
                    marketPrice: 15.0 // price per lb
                },
            
                // Subtropical Plants (31-60)
                {
                    id: 31,
                    name: 'Avocado',
                    layer: 'Canopy',
                    climate: 'Subtropical',
                    symbol: '🥑',
                    yieldPerYear: 154,
                    unit: 'lbs',
                    maturityAge: 4,
                    scientificName: 'Persea americana',
                    description: 'Evergreen tree producing nutrient-dense fruits.',
                    uses: ['Food', 'Oil'],
                    growthHabit: 'Evergreen tree, can reach 60 feet',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun',
                    water: 'Moderate, sensitive to overwatering',
                    companions: ['Lemon', 'Comfrey', 'Nasturtium'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Persea_americana_fruit_2.JPG/1024px-Persea_americana_fruit_2.JPG',
                    marketPrice: 4.0 // price per lb
                },
                {
                    id: 32,
                    name: 'Lemon Tree',
                    layer: 'Sub-canopy',
                    climate: 'Subtropical',
                    symbol: '🍋',
                    yieldPerYear: 88,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Citrus limon',
                    description: 'Small evergreen tree producing tart citrus fruits.',
                    uses: ['Food', 'Cleaning', 'Medicinal'],
                    growthHabit: 'Small tree, 10-20 feet tall',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Lavender', 'Marigold', 'Garlic'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/e/e4/P1030323.JPG',
                    marketPrice: 6.0 // price per lb
                },
                {
                    id: 33,
                    name: 'Fig Tree',
                    layer: 'Sub-canopy',
                    climate: 'Subtropical',
                    symbol: '🧅',
                    yieldPerYear: 44,
                    unit: 'lbs',
                    maturityAge: 4,
                    scientificName: 'Ficus carica',
                    description: 'Deciduous tree producing sweet fruits.',
                    uses: ['Food', 'Medicine'],
                    growthHabit: 'Small tree or large shrub, 10-30 feet tall',
                    soil: 'Well-draining, tolerates various types',
                    sunlight: 'Full sun',
                    water: 'Moderate, drought-tolerant when established',
                    companions: ['Comfrey', 'Nasturtium', 'Borage'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/0/04/Fig.jpg',
                    marketPrice: 8.0 // price per lb
                },
                {
                    id: 34,
                    name: 'Pomegranate',
                    layer: 'Shrub',
                    climate: 'Subtropical',
                    symbol: '🎄',
                    yieldPerYear: 33,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Punica granatum',
                    description: 'Fruit-bearing shrub with distinctive red seeds.',
                    uses: ['Food', 'Medicine', 'Dye'],
                    growthHabit: 'Large shrub or small tree, 6-15 feet tall',
                    soil: 'Well-draining, tolerates various types',
                    sunlight: 'Full sun',
                    water: 'Moderate, drought-tolerant when established',
                    companions: ['Lavender', 'Rosemary', 'Thyme'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Pomegranate_%28opened%29.jpg/1920px-Pomegranate_%28opened%29.jpg',
                    marketPrice: 10.0 // price per lb
                },
                {
                    id: 35,
                    name: 'Rosemary',
                    layer: 'Herbaceous',
                    climate: 'Subtropical',
                    symbol: '🌿',
                    yieldPerYear: 2.2,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Salvia rosmarinus',
                    description: 'Aromatic evergreen shrub used as a culinary herb.',
                    uses: ['Culinary', 'Medicinal', 'Ornamental'],
                    growthHabit: 'Evergreen shrub, 3-5 feet tall',
                    soil: 'Well-draining, sandy',
                    sunlight: 'Full sun',
                    water: 'Low, drought-tolerant',
                    companions: ['Sage', 'Thyme', 'Lavender'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Rosemary_in_bloom.JPG',
                    marketPrice: 12.0 // price per lb
                },
                {
                    id: 36,
                    name: 'Orange Tree',
                    layer: 'Canopy',
                    climate: 'Subtropical',
                    symbol: '🍊',
                    yieldPerYear: 110,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Citrus × sinensis',
                    description: 'Evergreen tree producing sweet orange fruits.',
                    uses: ['Food', 'Juice', 'Essential oil'],
                    growthHabit: 'Evergreen tree, 20-30 feet tall',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Nasturtium', 'Comfrey', 'Lemon Balm'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/OrangeBloss_wb.jpg',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 37,
                    name: 'Peach Tree',
                    layer: 'Canopy',
                    climate: 'Subtropical',
                    symbol: '🍑',
                    yieldPerYear: 66,
                    unit: 'lbs',
                    maturityAge: 4,
                    scientificName: 'Prunus persica',
                    description: 'Deciduous tree known for its sweet, juicy fruits.',
                    uses: ['Food', 'Cosmetics'],
                    growthHabit: 'Deciduous tree, 15-25 feet tall',
                    soil: 'Well-draining, sandy loam',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Garlic', 'Tansy', 'Borage'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Illustration_Prunus_persica0.jpg/800px-Illustration_Prunus_persica0.jpg',
                    marketPrice: 7.0 // price per lb
                },
                {
                    id: 38,
                    name: 'Macadamia Nut',
                    layer: 'Canopy',
                    climate: 'Subtropical',
                    symbol: '🥜',
                    yieldPerYear: 22,
                    unit: 'lbs',
                    maturityAge: 7,
                    scientificName: 'Macadamia integrifolia',
                    description: 'Evergreen tree producing rich, buttery nuts.',
                    uses: ['Food', 'Oil'],
                    growthHabit: 'Evergreen tree, 30-40 feet tall',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Pigeon Pea', 'Comfrey', 'Sweet Potato'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Macadamia_nuts_on_tree.JPG/1024px-Macadamia_nuts_on_tree.JPG',
                    marketPrice: 15.0 // price per lb
                },
                {
                    id: 39,
                    name: 'Olive Tree',
                    layer: 'Sub-canopy',
                    climate: 'Subtropical',
                    symbol: '🫒',
                    yieldPerYear: 44,
                    unit: 'lbs',
                    maturityAge: 5,
                    scientificName: 'Olea europaea',
                    description: 'Long-lived evergreen tree producing edible fruits and oil.',
                    uses: ['Food', 'Oil', 'Wood'],
                    growthHabit: 'Evergreen tree, 20-30 feet tall',
                    soil: 'Well-draining, tolerates poor soil',
                    sunlight: 'Full sun',
                    water: 'Low, drought-tolerant',
                    companions: ['Lavender', 'Rosemary', 'Thyme'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Olivesfromjordan.jpg',
                    marketPrice: 10.0 // price per lb
                },
                {
                    id: 40,
                    name: 'Persimmon',
                    layer: 'Sub-canopy',
                    climate: 'Subtropical',
                    symbol: '🍅',
                    yieldPerYear: 55,
                    unit: 'lbs',
                    maturityAge: 4,
                    scientificName: 'Diospyros kaki',
                    description: 'Deciduous tree with sweet, orange fruits.',
                    uses: ['Food', 'Wood'],
                    growthHabit: 'Deciduous tree, 20-30 feet tall',
                    soil: 'Well-draining, tolerates various types',
                    sunlight: 'Full sun',
                    water: 'Moderate, tolerates brief dry periods',
                    companions: ['Comfrey', 'Borage', 'Yarrow'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Persimmons_at_Bilpin-Pine_Crest.jpg/800px-Persimmons_at_Bilpin-Pine_Crest.jpg',
                    marketPrice: 8.0 // price per lb
                },
                {
                    id: 41,
                    name: 'Loquat',
                    layer: 'Sub-canopy',
                    climate: 'Subtropical',
                    symbol: '🍐',
                    yieldPerYear: 33,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Eriobotrya japonica',
                    description: 'Evergreen tree with edible yellow fruits.',
                    uses: ['Food', 'Medicinal'],
                    growthHabit: 'Evergreen tree, 20-30 feet tall',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, tolerates brief dry periods',
                    companions: ['Nasturtium', 'Comfrey', 'Chives'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Loquat-0.jpg/1024px-Loquat-0.jpg',
                    marketPrice: 12.0 // price per lb
                },
                {
                    id: 42,
                    name: 'Pineapple Guava',
                    layer: 'Shrub',
                    climate: 'Subtropical',
                    symbol: '🌺',
                    yieldPerYear: 22,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Acca sellowiana',
                    description: 'Evergreen shrub producing aromatic, guava-like fruits.',
                    uses: ['Food', 'Ornamental'],
                    growthHabit: 'Evergreen shrub, 10-15 feet tall',
                    soil: 'Well-draining, tolerates various types',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, drought-tolerant when established',
                    companions: ['Comfrey', 'Borage', 'Nasturtium'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Acca_sellowiana_Fruit_MHNT_Fronton.jpg/1920px-Acca_sellowiana_Fruit_MHNT_Fronton.jpg',
                    marketPrice: 8.0 // price per lb
                },
                {
                    id: 43,
                    name: 'Kumquat',
                    layer: 'Shrub',
                    climate: 'Subtropical',
                    symbol: '🍊',
                    yieldPerYear: 11,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Citrus japonica',
                    description: 'Small evergreen tree or large shrub with small, edible citrus fruits.',
                    uses: ['Food', 'Ornamental'],
                    growthHabit: 'Evergreen shrub or small tree, 8-15 feet tall',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture', // Completed property
                    companions: ['Nasturtium', 'Marigold', 'Comfrey'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/7/72/Kumquat_from_Spain.jpg',
                    marketPrice: 10.0 // price per lb    
                },
                {
                    id: 44,
                    name: 'Goji Berry',
                    layer: 'Shrub',
                    climate: 'Subtropical',
                    symbol: '🫐',
                    yieldPerYear: 4.4,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Lycium barbarum',
                    description: 'Deciduous woody shrub known for its nutrient-rich berries.',
                    uses: ['Food', 'Medicinal'],
                    growthHabit: 'Deciduous shrub, 3-6 feet tall',
                    soil: 'Well-draining, tolerates various types',
                    sunlight: 'Full sun',
                    water: 'Low, drought-tolerant',
                    companions: ['Marigold', 'Borage', 'Yarrow'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Wolfberries_China_7-05.JPG/1024px-Wolfberries_China_7-05.JPG',
                    marketPrice: 8.0 // price per lb
                },
                {
                    id: 45,
                    name: 'Aloe Vera',
                    layer: 'Herbaceous',
                    climate: 'Subtropical',
                    symbol: '🌵',
                    yieldPerYear: 4.4,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Aloe barbadensis miller',
                    description: 'Succulent plant with medicinal and cosmetic uses.',
                    uses: ['Medicinal', 'Cosmetic'],
                    growthHabit: 'Succulent, forms clumps 1-2 feet tall',
                    soil: 'Well-draining, sandy',
                    sunlight: 'Full sun to partial shade',
                    water: 'Low, drought-tolerant',
                    companions: ['Cacti', 'Agave', 'Yucca'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Aloe_vera_flower_inset.png',
                    marketPrice: 6.0 // price per lb
                },
                {
                    id: 46,
                    name: 'Lemongrass',
                    layer: 'Herbaceous',
                    climate: 'Subtropical',
                    symbol: '🌿',
                    yieldPerYear: 2.2,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Cymbopogon citratus',
                    description: 'Tropical grass with a lemony scent, used in cooking and tea.',
                    uses: ['Culinary', 'Medicinal', 'Essential oil'],
                    growthHabit: 'Grass, forms clumps 3-5 feet tall',
                    soil: 'Well-draining, fertile',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Cilantro', 'Basil', 'Marigold'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/YosriNov04Pokok_Serai.JPG',
                    marketPrice: 4.0 // price per lb
                },
                {
                    id: 47,
                    name: 'Artichoke',
                    layer: 'Herbaceous',
                    climate: 'Subtropical',
                    symbol: '🌺',
                    yieldPerYear: 6.6,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Cynara cardunculus var. scolymus',
                    description: 'Perennial thistle cultivated for its edible flower buds.',
                    uses: ['Food', 'Medicinal'],
                    growthHabit: 'Perennial thistle, 3-5 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Sunflower', 'Tarragon', 'Borage'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Artichoke_J1.jpg/1024px-Artichoke_J1.jpg',
                    marketPrice: 12.0 // price per lb
                },
                {
                    id: 48,
                    name: 'Strawberry Guava',
                    layer: 'Shrub',
                    climate: 'Subtropical',
                    symbol: '🍓',
                    yieldPerYear: 11,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Psidium cattleianum',
                    description: 'Small tree or shrub producing sweet, red fruits.',
                    uses: ['Food', 'Jam'],
                    growthHabit: 'Evergreen shrub or small tree, 6-14 feet tall',
                    soil: 'Well-draining, acidic',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, tolerates brief dry periods',
                    companions: ['Pineapple', 'Sweet Potato', 'Nasturtium'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/9/97/Psidium_cattleianum_fruit.jpg',
                    marketPrice: 9.0 // price per lb
                },
                {
                    id: 49,
                    name: 'Passionfruit',
                    layer: 'Vine',
                    climate: 'Subtropical',
                    symbol: '🟢',
                    yieldPerYear: 22,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Passiflora edulis',
                    description: 'Vigorous vine producing tart, edible fruits.',
                    uses: ['Food', 'Juice'],
                    growthHabit: 'Climbing vine, can reach 20 feet',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Banana', 'Sweet Potato', 'Marigold'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Passion_fruits_-_whole_and_halved.jpg/330px-Passion_fruits_-_whole_and_halved.jpg',
                    marketPrice: 11.0 // price per lb
                },
                {
                    id: 50,
                    name: 'Kiwi',
                    layer: 'Vine',
                    climate: 'Subtropical',
                    symbol: '🥝',
                    yieldPerYear: 33,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Actinidia deliciosa',
                    description: 'Woody vine producing fuzzy, brown fruits with green flesh.',
                    uses: ['Food'],
                    growthHabit: 'Woody vine, can reach 30 feet',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Comfrey', 'Yarrow', 'Borage'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/5/58/Kiwifruit-Actinidia_deliciosa-plantation.jpg',
                    marketPrice: 10.0 // price per lb
                },
                // Continue with plants 51-60 for subtropical climate
            
                // Temperate Plants (61-90)
                {
                    id: 61,
                    name: 'Apple Tree',
                    layer: 'Canopy',
                    climate: 'Temperate',
                    symbol: '🍎',
                    yieldPerYear: 176,
                    unit: 'lbs',
                    maturityAge: 5,
                    scientificName: 'Malus domestica',
                    description: 'Deciduous tree producing crisp, sweet fruits.',
                    uses: ['Food', 'Cider', 'Wood'],
                    growthHabit: 'Deciduous tree, 15-30 feet tall',
                    soil: 'Well-draining, loamy',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Nasturtium', 'Comfrey', 'Garlic'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Malus_domestica_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-108.jpg',
                    marketPrice: 4.0 // price per lb
                },
                {
                    id: 62,
                    name: 'Pear Tree',
                    layer: 'Canopy',
                    climate: 'Temperate',
                    symbol: '🍐',
                    yieldPerYear: 154,
                    unit: 'lbs',
                    maturityAge: 5,
                    scientificName: 'Pyrus communis',
                    description: 'Deciduous tree producing sweet, juicy fruits.',
                    uses: ['Food', 'Wood'],
                    growthHabit: 'Deciduous tree, 30-50 feet tall',
                    soil: 'Well-draining, loamy',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Garlic', 'Comfrey', 'Daffodils'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Pears.jpg',
                    marketPrice: 4.0 // price per lb
                },
                {
                    id: 63,
                    name: 'Cherry Tree',
                    layer: 'Canopy',
                    climate: 'Temperate',
                    symbol: '🍒',
                    yieldPerYear: 110,
                    unit: 'lbs',
                    maturityAge: 4,
                    scientificName: 'Prunus avium',
                    description: 'Deciduous tree known for its sweet or tart fruits.',
                    uses: ['Food', 'Wood', 'Ornamental'],
                    growthHabit: 'Deciduous tree, 20-40 feet tall',
                    soil: 'Well-draining, fertile',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Marigold', 'Chives', 'Dandelion'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Cherry_season_%2848216568227%29.jpg/800px-Cherry_season_%2848216568227%29.jpg',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 64,
                    name: 'Plum Tree',
                    layer: 'Canopy',
                    climate: 'Temperate',
                    symbol: '🍑',
                    yieldPerYear: 88,
                    unit: 'lbs',
                    maturityAge: 4,
                    scientificName: 'Prunus domestica',
                    description: 'Deciduous tree producing juicy, sweet-tart fruits.',
                    uses: ['Food', 'Medicinal'],
                    growthHabit: 'Deciduous tree, 15-30 feet tall',
                    soil: 'Well-draining, fertile',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Comfrey', 'Nasturtium', 'Allium'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/%C5%A0ljiva_Stanley_-_zeleni_plodovi.2.jpg/800px-%C5%A0ljiva_Stanley_-_zeleni_plodovi.2.jpg://example.com/plum-tree.jpg',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 65,
                    name: 'Chestnut',
                    layer: 'Canopy',
                    climate: 'Temperate',
                    symbol: '🌰',
                    yieldPerYear: 55,
                    unit: 'lbs',
                    maturityAge: 7,
                    scientificName: 'Castanea sativa',
                    description: 'Deciduous tree producing edible nuts.',
                    uses: ['Food', 'Wood', 'Tannin'],
                    growthHabit: 'Deciduous tree, 50-100 feet tall',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun',
                    water: 'Moderate, tolerates brief dry periods',
                    companions: ['Comfrey', 'Yarrow', 'Clover'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Ch%C3%A2taignier_120807_1.jpg/1280px-Ch%C3%A2taignier_120807_1.jpg',
                    marketPrice: 5.0 // price per lb
                },
                    {
                    id: 66,
                    name: 'Hazelnut',
                    layer: 'Sub-canopy',
                    climate: 'Temperate',
                    symbol: '🌰',
                    yieldPerYear: 6.6,
                    unit: 'lbs',
                    maturityAge: 4,
                    scientificName: 'Corylus avellana',
                    description: 'Deciduous shrub or small tree producing edible nuts.',
                    uses: ['Food', 'Oil', 'Crafts'],
                    growthHabit: 'Multi-stemmed shrub or small tree, 10-20 feet tall',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, tolerates some drought',
                    companions: ['Comfrey', 'Yarrow', 'Daffodils'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Corylus_colurna_%281%29.JPG/800px-Corylus_colurna_%281%29.JPG',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 67,
                    name: 'Elderberry',
                    layer: 'Sub-canopy',
                    climate: 'Temperate',
                    symbol: '💜',
                    yieldPerYear: 11,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Sambucus nigra',
                    description: 'Deciduous shrub with edible berries and medicinal flowers.',
                    uses: ['Food', 'Medicinal', 'Dye'],
                    growthHabit: 'Deciduous shrub or small tree, 10-20 feet tall',
                    soil: 'Moist, rich in organic matter',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate to high, prefers consistent moisture',
                    companions: ['Comfrey', 'Yarrow', 'Mint'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Sambucus-berries.jpg/1280px-Sambucus-berries.jpg',
                    marketPrice: 8.0 // price per lb
                },
                {
                    id: 68,
                    name: 'Pawpaw',
                    layer: 'Sub-canopy',
                    climate: 'Temperate',
                    symbol: '💚',
                    yieldPerYear: 22,
                    unit: 'lbs',
                    maturityAge: 5,
                    scientificName: 'Asimina triloba',
                    description: 'Small tree producing large, custard-like fruits.',
                    uses: ['Food'],
                    growthHabit: 'Deciduous tree, 15-30 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Comfrey', 'Wild Ginger', 'Spicebush'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Asimina_triloba3.jpg/1280px-Asimina_triloba3.jpg',
                    marketPrice: 6.0 // price per lb
                },
                {
                    id: 69,
                    name: 'Serviceberry',
                    layer: 'Sub-canopy',
                    climate: 'Temperate',
                    symbol: '🫐',
                    yieldPerYear: 8.8,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Amelanchier spp.',
                    description: 'Small tree or shrub with edible berries.',
                    uses: ['Food', 'Ornamental'],
                    growthHabit: 'Deciduous shrub or small tree, 15-25 feet tall',
                    soil: 'Well-draining, tolerates various types',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, tolerates brief dry periods',
                    companions: ['Blueberry', 'Chokeberry', 'Wild Strawberry'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Amelanchier_alnifolia_6338.JPG/800px-Amelanchier_alnifolia_6338.JPG',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 70,
                    name: 'Quince',
                    layer: 'Sub-canopy',
                    climate: 'Temperate',
                    symbol: '🟡',
                    yieldPerYear: 33,
                    unit: 'lbs',
                    maturityAge: 4,
                    scientificName: 'Cydonia oblonga',
                    description: 'Small tree producing aromatic fruits used in preserves.',
                    uses: ['Food', 'Medicinal'],
                    growthHabit: 'Deciduous small tree, 10-20 feet tall',
                    soil: 'Well-draining, tolerates various types',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Comfrey', 'Yarrow', 'Nasturtium'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Quince_in_Fergana.jpg/1280px-Quince_in_Fergana.jpg',
                    marketPrice: 7.0 // price per lb
                },
                {
                    id: 71,
                    name: 'Blueberry',
                    layer: 'Shrub',
                    climate: 'Temperate',
                    symbol: '🫐',
                    yieldPerYear: 8.8,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Vaccinium corymbosum',
                    description: 'Deciduous shrub producing sweet berries.',
                    uses: ['Food', 'Medicine'],
                    growthHabit: 'Deciduous shrub, 4-6 feet tall',
                    soil: 'Well-draining, acidic',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Strawberry', 'Rhododendron', 'Pine'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/1/15/Blueberries.jpg',
                    marketPrice: 6.0 // price per lb
                },
                {
                    id: 72,
                    name: 'Raspberry',
                    layer: 'Shrub',
                    climate: 'Temperate',
                    symbol: '🍇',
                    yieldPerYear: 4.4,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Rubus idaeus',
                    description: 'Thorny shrub producing sweet, aggregate fruits.',
                    uses: ['Food', 'Medicinal'],
                    growthHabit: 'Deciduous shrub, 4-6 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Garlic', 'Tansy', 'Yarrow'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Fert%C5%91di_k%C3%A1rmin_m%C3%A1lna.JPG/1280px-Fert%C5%91di_k%C3%A1rmin_m%C3%A1lna.JPG',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 73,
                    name: 'Blackberry',
                    layer: 'Shrub',
                    climate: 'Temperate',
                    symbol: '🫐',
                    yieldPerYear: 6.6,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Rubus fruticosus',
                    description: 'Thorny shrub producing sweet, aggregate fruits.',
                    uses: ['Food', 'Medicinal'],
                    growthHabit: 'Deciduous shrub, 3-6 feet tall',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Tansy', 'Borage', 'Comfrey'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Ripe%2C_ripening%2C_and_green_blackberries.jpg/1280px-Ripe%2C_ripening%2C_and_green_blackberries.jpg',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 74,
                    name: 'Gooseberry',
                    layer: 'Shrub',
                    climate: 'Temperate',
                    symbol: '🫐',
                    yieldPerYear: 4.4,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Ribes uva-crispa',
                    description: 'Thorny shrub producing tart berries.',
                    uses: ['Food'],
                    growthHabit: 'Deciduous shrub, 3-5 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Tomato', 'Tansy', 'Oregano'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Stachelbeere_%28Ribes_uva-crispa%29.jpg',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 75,
                    name: 'Currant',
                    layer: 'Shrub',
                    climate: 'Temperate',
                    symbol: '🟠',
                    yieldPerYear: 4.4,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Ribes rubrum',
                    description: 'Deciduous shrub producing tart berries in clusters.',
                    uses: ['Food', 'Medicinal'],
                    growthHabit: 'Deciduous shrub, 3-5 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Comfrey', 'Tansy', 'Beans'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Ribes_rubrum_a1.jpg',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 76,
                    name: 'Rhubarb',
                    layer: 'Herbaceous',
                    climate: 'Temperate',
                    symbol: '🥬',
                    yieldPerYear: 4.4,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Rheum rhabarbarum',
                    description: 'Perennial vegetable known for its tart, edible stalks.',
                    uses: ['Food', 'Medicinal'],
                    growthHabit: 'Herbaceous perennial, 2-3 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Strawberry', 'Garlic', 'Brassicas'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Rheum_rhabarbarum.2006-04-27.uellue.jpg/1280px-Rheum_rhabarbarum.2006-04-27.uellue.jpg',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 77,
                    name: 'Asparagus',
                    layer: 'Herbaceous',
                    climate: 'Temperate',
                    symbol: '🎋',
                    yieldPerYear: 2.2,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Asparagus officinalis',
                    description: 'Perennial vegetable prized for its tender, young shoots.',
                    uses: ['Food', 'Medicinal'],
                    growthHabit: 'Herbaceous perennial, 4-5 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Tomato', 'Parsley', 'Basil'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Asparagus_Tip.jpg/800px-Asparagus_Tip.jpg',
                    marketPrice: 6.0 // price per lb   
                },
                {
                    id: 78,
                    name: 'Horseradish',
                    layer: 'Root',
                    climate: 'Temperate',
                    symbol: '🐎',
                    yieldPerYear: 1.1,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Armoracia rusticana',
                    description: 'Perennial root vegetable known for its pungent flavor.',
                    uses: ['Food', 'Medicinal'],
                    growthHabit: 'Herbaceous perennial, 2-3 feet tall',
                    soil: 'Well-draining, deep',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, tolerates dry periods',
                    companions: ['Potato', 'Sweet Potato', 'Strawberry'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Armoracia_rusticana.jpg/800px-Armoracia_rusticana.jpghttps://example.com/horseradish.jpg',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 79,
                    name: 'Mint',
                    layer: 'Ground Cover',
                    climate: 'Temperate',
                    symbol: '🍬',
                    yieldPerYear: 1.1,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Mentha spp.',
                    description: 'Aromatic herb known for its culinary and medicinal uses.',
                    uses: ['Culinary', 'Medicinal', 'Pest control'],
                    growthHabit: 'Herbaceous perennial, 1-2 feet tall, spreading',
                    soil: 'Moist, rich in organic matter',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate to high, prefers consistent moisture',
                    companions: ['Cabbage', 'Tomato', 'Carrots'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/9/94/Leucas_aspera_at_Gandipet%2C_Hyderabad%2C_AP_W_IMG_9054.jpg',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 80,
                    name: 'Strawberry',
                    layer: 'Ground Cover',
                    climate: 'Temperate',
                    symbol: '🍓',
                    yieldPerYear: 1.1,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Fragaria × ananassa',
                    description: 'Low-growing perennial producing sweet, red fruits.',
                    uses: ['Food', 'Groundcover'],
                    growthHabit: 'Herbaceous perennial, 6-12 inches tall, spreading',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Borage', 'Lettuce', 'Spinach'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg/1280px-Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 81,
                    name: 'Grape',
                    layer: 'Vine',
                    climate: 'Temperate',
                    symbol: '🍇',
                    yieldPerYear: 22,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Vitis vinifera',
                    description: 'Woody vine producing sweet, edible fruits.',
                    uses: ['Food', 'Beverage', 'Shade'],
                    growthHabit: 'Woody vine, can reach 50+ feet',
                    soil: 'Well-draining, slightly acidic',
                    sunlight: 'Full sun',
                    water: 'Moderate, tolerates some drought when established',
                    companions: ['Hyssop', 'Chives', 'Mulberry'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Abhar-iran.JPG',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 82,
                    name: 'Kiwi',
                    layer: 'Vine',
                    climate: 'Temperate',
                    symbol: '🥝',
                    yieldPerYear: 33,
                    unit: 'lbs',
                    maturityAge: 4,
                    scientificName: 'Actinidia deliciosa',
                    description: 'Woody vine producing fuzzy, edible fruits.',
                    uses: ['Food'],
                    growthHabit: 'Woody vine, can reach 30 feet',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Comfrey', 'Yarrow', 'Nasturtium'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/5/58/Kiwifruit-Actinidia_deliciosa-plantation.jpg',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 83,
                    name: 'Hops',
                    layer: 'Vine',
                    climate: 'Temperate',
                    symbol: '🌿',
                    yieldPerYear: 2.2,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Humulus lupulus',
                    description: 'Perennial vine known for its use in beer production.',
                    uses: ['Beverage', 'Medicinal'],
                    growthHabit: 'Herbaceous perennial vine, can reach 20 feet',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Pole Beans', 'Sunflowers', 'Marigolds'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Hopfendolde-mit-hopfengarten.jpg/1280px-Hopfendolde-mit-hopfengarten.jpg',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 84,
                    name: 'Sunchoke',
                    layer: 'Root',
                    climate: 'Temperate',
                    symbol: '🥔',
                    yieldPerYear: 6.6,
                    unit: 'lbs',
                    maturityAge: 1,
                    scientificName: 'Helianthus tuberosus',
                    description: 'Sunflower relative grown for its edible tubers.',
                    uses: ['Food', 'Animal feed'],
                    growthHabit: 'Herbaceous perennial, 6-10 feet tall',
                    soil: 'Well-draining, tolerates poor soil',
                    sunlight: 'Full sun',
                    water: 'Moderate, tolerates drought',
                    companions: ['Corn', 'Squash', 'Sunflowers'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Sunroot_top.jpg/800px-Sunroot_top.jpg',
                    marketPrice: 6.0 // price per lb
                },
                {
                    id: 85,
                    name: 'Walnut',
                    layer: 'Canopy',
                    climate: 'Temperate',
                    symbol: '🌰',
                    yieldPerYear: 66,
                    unit: 'lbs',
                    maturityAge: 8,
                    scientificName: 'Juglans regia',
                    description: 'Large deciduous tree producing edible nuts.',
                    uses: ['Food', 'Timber', 'Dye'],
                    growthHabit: 'Deciduous tree, 40-60 feet tall',
                    soil: 'Deep, well-draining',
                    sunlight: 'Full sun',
                    water: 'Moderate, tolerates drought when established',
                    companions: ['Comfrey', 'Daffodils', 'Bluebells'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Walnuts_-_whole_and_open_with_halved_kernel.jpg/1280px-Walnuts_-_whole_and_open_with_halved_kernel.jpg',
                    marketPrice: 5.0 // price per lb
                },
                {
                    id: 86,
                    name: 'Pecan',
                    layer: 'Canopy',
                    climate: 'Temperate',
                    symbol: '🥜',
                    yieldPerYear: 44,
                    unit: 'lbs',
                    maturityAge: 7,
                    scientificName: 'Carya illinoinensis',
                    description: 'Large deciduous tree producing sweet, edible nuts.',
                    uses: ['Food', 'Timber'],
                    growthHabit: 'Deciduous tree, 70-100 feet tall',
                    soil: 'Deep, well-draining',
                    sunlight: 'Full sun',
                    water: 'Moderate, consistent moisture',
                    companions: ['Clover', 'Vetch', 'Native grasses'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Carya_illinoinensis.jpg/800px-Carya_illinoinensis.jpg',
                    marketPrice: 3.0 // price per lb
                },
                {
                    id: 87,
                    name: 'Persimmon',
                    layer: 'Sub-canopy',
                    climate: 'Temperate',
                    symbol: '🍅',
                    yieldPerYear: 44,
                    unit: 'lbs',
                    maturityAge: 5,
                    scientificName: 'Diospyros virginiana',
                    description: 'Deciduous tree producing sweet, orange fruits.',
                    uses: ['Food', 'Wood'],
                    growthHabit: 'Deciduous tree, 30-50 feet tall',
                    soil: 'Well-draining, tolerates various types',
                    sunlight: 'Full sun',
                    water: 'Moderate, tolerates brief dry periods',
                    companions: ['Comfrey', 'Yarrow', 'Wild Strawberry'],
                    image: 'https://examhttps://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Fuyu_persimmon_fruits%2C_one_cut_open.jpg/1280px-Fuyu_persimmon_fruits%2C_one_cut_open.jpg',
                    marketPrice: 4.0 // price per lb
                },
                {
                    id: 88,
                    name: 'Sea Buckthorn',
                    layer: 'Shrub',
                    climate: 'Temperate',
                    symbol: '🍊',
                    yieldPerYear: 11,
                    unit: 'lbs',
                    maturityAge: 4,
                    scientificName: 'Hippophae rhamnoides',
                    description: 'Deciduous shrub producing nutrient-rich berries.',
                    uses: ['Food', 'Medicinal', 'Erosion control'],
                    growthHabit: 'Deciduous shrub, 6-20 feet tall',
                    soil: 'Well-draining, tolerates poor soil',
                    sunlight: 'Full sun',
                    water: 'Low, drought-tolerant',
                    companions: ['Legumes', 'Comfrey', 'Yarrow'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Hippophae_rhamnoides-01_%28xndr%29.JPG/800px-Hippophae_rhamnoides-01_%28xndr%29.JPG',
                    marketPrice: 2.0 // price per lb
                },
                {
                    id: 89,
                    name: 'Goumi',
                    layer: 'Shrub',
                    climate: 'Temperate',
                    symbol: '🍒',
                    yieldPerYear: 4.4,
                    unit: 'lbs',
                    maturityAge: 3,
                    scientificName: 'Elaeagnus multiflora',
                    description: 'Deciduous shrub producing tart, edible berries.',
                    uses: ['Food', 'Nitrogen fixation'],
                    growthHabit: 'Deciduous shrub, 6-10 feet tall',
                    soil: 'Well-draining, tolerates poor soil',
                    sunlight: 'Full sun to partial shade',
                    water: 'Low, drought-tolerant',
                    companions: ['Comfrey', 'Yarrow', 'Chives'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Goumi-fruits.jpg/800px-Goumi-fruits.jpg',
                    marketPrice: 3.0 // price per lb
                },
                {
                    id: 90,
                    name: 'Lovage',
                    layer: 'Herbaceous',
                    climate: 'Temperate',
                    symbol: '🌿',
                    yieldPerYear: 1.1,
                    unit: 'lbs',
                    maturityAge: 2,
                    scientificName: 'Levisticum officinale',
                    description: 'Tall perennial herb with a strong celery-like flavor.',
                    uses: ['Culinary', 'Medicinal'],
                    growthHabit: 'Herbaceous perennial, 3-6 feet tall',
                    soil: 'Well-draining, rich in organic matter',
                    sunlight: 'Full sun to partial shade',
                    water: 'Moderate, consistent moisture',
                    companions: ['Dill', 'Fennel', 'Anise'],
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Liebst%C3%B6ckel.JPG/800px-Liebst%C3%B6ckel.JPG',
                    marketPrice: 2.0 // price per lb
                },
          // Add more plants here...
  
        ];

